### ISSUE TITLE
Cart: Complete Purchase

### ISSUE THREAD

**Issue by caestrella1** [cestrrada/MovieRental#3]
The grand total is never saved to the database after completing a purchase, resulting in the aggregate function for average order not working. Need to fix this in `addItemToOrder.php` and `cart.js`.

**Comment by trfoss** [comment]
Fixing right now.

**Comment by trfoss** [comment]
So there are two ways we can approach this:
1) The way I originally had the tables set up, was to be able to natural join very easily. In order to get the total of a completed cart, we just need to use this query (or something very similar): ```select SUM(itemPrice) from orderHistory natural join itemTable where conNum=$conNum```,  but the issue here is were missing tax and any promo codes applied, so we'd need a way to include these somehow. So I suggest...
2) Just adding the grand total in the price column in orderHistory, but this takes away the need for an aggregate function to sum up order totals, this would be nice though because its a very easy fix

Let me know

**Comment by trfoss** [comment]
So I think the easiest way would be to add the grand total to the price column in the order history table. But I'm worried this would take the need away for the use of a SUM aggregate function, is this an issue or not?

**Comment by trfoss** [comment]
I think this is good, if someone could verify I'd appreciate it

**Comment by trfoss** [comment]
Now the price column is the order total, so I'm not sure if this effects any code any where else, if it does we can just revert back to an older version
